- merch-dropper/public/index.html
- merch-dropper/src/App.js
- merch-dropper/src/actions/index.js
- merch-dropper/src/components/CloudinaryWidget.js
- merch-dropper/src/components/Home.js
- merch-dropper/src/components/NavBar.js
- merch-dropper/src/components/ProductCard.js
- merch-dropper/src/components/ProductDisplay.js
- merch-dropper/src/components/ShoppingCart.js
- merch-dropper/src/components/ShoppingCartItem.js
- merch-dropper/src/reducers/CartReducers.js
> Shopping cart

- merch-dropper/src/components/Homepage.js
> Fixed hero image error

- merch-dropper/src/App.js
- merch-dropper/src/actions/index.js
- merch-dropper/src/components/NavBar.js
> Shirt Design rerouting

- merch-dropper/src/App.js
- merch-dropper/src/components/CloudinaryWidget.js
- merch-dropper/src/components/Shirt/DesignShirt.js
- merch-dropper/src/components/Shirt/HorizontalAlign.js
- merch-dropper/src/components/Shirt/MockupDisplay.js
- merch-dropper/src/components/Shirt/SizeSlider.js
- merch-dropper/src/components/Shirt/StoreHandler.js
- merch-dropper/src/components/Shirt/Swatch.js
- merch-dropper/src/components/Shirt/TemplateShirt.js
- merch-dropper/src/components/Shirt/ThumbDisplay.js
Makes shirt making more robust and aesthetic
- [x ] Complete, but not tested (may need new tests)
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
> updated app.js

- merch-dropper/src/App.js
- merch-dropper/src/components/CloudinaryWidget.js
- merch-dropper/src/components/NavBar.js
- merch-dropper/src/components/Search.js
- merch-dropper/src/store/actions/index.js
- merch-dropper/src/store/reducers/SearchReducers.js
- merch-dropper/src/store/reducers/index.js
> Plain login reg

- merch-dropper/src/App.css
- merch-dropper/src/App.js
- merch-dropper/src/components/Footer.js
- merch-dropper/src/components/Homepage.js
> Edited footer styling

- merch-dropper/.babelrc
- merch-dropper/package-lock.json
- merch-dropper/package.json
- merch-dropper/src/App.css
- merch-dropper/src/components/Home.js
- merch-dropper/src/components/NavBar.js
- merch-dropper/src/components/StripeButton.js
> fixes cart bug, nav bug, and stripe bug

- merch-dropper/package.json
- merch-dropper/public/index.html
- merch-dropper/src/components/Cart/CartIcon.js
- merch-dropper/src/components/Footer.js
- merch-dropper/src/components/LearnMore.js
- merch-dropper/src/components/NavBar.js
- merch-dropper/src/components/Search.js
- merch-dropper/src/components/SideDrawer.js
- merch-dropper/src/index.js
- merch-dropper/yarn.lock
> Navbarstyling

- merch-dropper/package.json
- merch-dropper/src/App.js
- merch-dropper/src/components/Auth/SignUp.js
- merch-dropper/src/components/Onboarding/StripeCTA.js
- merch-dropper/src/components/Onboarding/StripeConnect.js
- merch-dropper/src/components/Onboarding/StripeSetup.js
- merch-dropper/src/components/Onboarding/Styled.js
- merch-dropper/yarn.lock
> Recloned from master to resolve yarn conflicts

- merch-dropper/__mocks__/fileMock.js
- merch-dropper/jest-transformer.js
- merch-dropper/package.json
- merch-dropper/src/__tests__/auth0.test.js
- merch-dropper/src/components/Cart/CartIcon.js
- merch-dropper/svgTransform.js
- merch-dropper/yarn.lock
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, tested, ready to review and merge
- [ x] Test A compared to clone application 
- [x ] My code has been reviewed by at least one peer
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
> auth0 test pass, recommiting for netlify deployment

- merch-dropper/src/App.js
- merch-dropper/src/components/ProductDisplayDomain.js
- merch-dropper/yarn.lock
- [x ] New feature (non-breaking change which adds functionality)
- [ x] Complete, but not tested (may need new tests)
- [ x] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
> ProductDisplayDomain name component

- merch-dropper/src/components/Onboarding/StripeConnect.js
> Fixed a routing issue

- merch-dropper/src/components/Redirect.js
- [x ] My changes generate no new warnings
> changed redirect route to stripe-setup

- merch-dropper/amplify.yml
> Aws deployment

- merch-dropper/amplify.yml
> changes to aws yml baseDirectory

- merch-dropper/src/App.js
- merch-dropper/src/components/Dashboard/Dashboard.js
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, tested, ready to review and merge
- [ x] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts
> Dash feat (fix dashboard routing and comp)

- merch-dropper/src/components/Redirect.js
> made super minor edit in redirect.js

- merch-dropper/src/components/Onboarding/StripeConnect.js
- merch-dropper/src/components/Shirt/AddProductToMerch.js
- merch-dropper/src/components/Shirt/DesignShirt.js
- [ x] Bug fix (non-breaking change which fixes an issue)
> changed url for skipping stripe connect

- merch-dropper/public/index.html
> added cookie_flags to index

- merch-dropper/src/__tests__/Navbar.test.js
- merch-dropper/src/components/Auth/Auth.js
- merch-dropper/src/components/NavBar.js
- merch-dropper/src/index.js
> Navbar feat

- merch-dropper/src/components/NavBar.js
> revert back to original code

- merch-dropper/yarn.lock
> updated auth0 package

- merch-dropper/src/components/Dashboard/Settings.js
- merch-dropper/src/components/NavBar.js
- merch-dropper/src/components/Onboarding/StripeConnect.js
Fixed a bug with stripe connect
> Settings dashboard feat

- merch-dropper/src/components/Shirt/AddProductToTable.js
> change file name path

- merch-dropper/src/components/Dashboard/Settings.js
> added axios with auth

- merch-dropper/src/components/Onboarding/StripeConnect.js
> attempting to fix a cors issue

- merch-dropper/src/components/Onboarding/StripeConnect.js
> reverted a merge change

- merch-dropper/src/components/NavBar.js
- merch-dropper/src/components/Shirt/AddProduct.js
- merch-dropper/src/components/Shirt/AddProductToTable.js
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, but not tested (may need new tests)
- [ x] My code follows the style guidelines of this project
- [ x] I have commented my code, particularly in hard-to-understand areas
> push to dash, GET url fixes

- merch-dropper/src/components/Dashboard/Settings.js
- merch-dropper/src/components/Onboarding/StripeConnect.js
> fixing an axios call

- merch-dropper/src/__tests__/__snapshots__/CreateStore.test.js.snap
- merch-dropper/src/__tests__/__snapshots__/Home.test.js.snap
- merch-dropper/src/__tests__/__snapshots__/ProductDisplayDomain.test.js.snap
- merch-dropper/src/__tests__/redirect.test.js
> edited tests to match changes in redirect.js

- merch-dropper/.babelrc
- merch-dropper/package.json
- merch-dropper/src/__tests__/AddProductToTable.test.js
- merch-dropper/src/components/Shirt/AddProductToTable.js
- merch-dropper/yarn.lock
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Complete, tested, ready to review and merge
- [x ] Test A
- [ x] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts
> test addproduct

- merch-dropper/src/components/Component-Styles/addProduct-styles.js
- [x ] Bug fix (non-breaking change which fixes an issue): Added padding on addproduct form 
- [ x] Complete, tested, ready to review and merge
> Add product test

- merch-dropper/src/components/Dashboard/Inventory.js
- merch-dropper/src/components/Dashboard/InventoryList.js
> Corrected styling of inventory component header

- merch-dropper/src/components/Dashboard/InventoryList.js
- merch-dropper/src/components/Dashboard/Settings.js
> Changed axiosWithAuth to axios on inventory component

- merch-dropper/src/components/Onboarding/StripeConnect.js
- merch-dropper/src/components/Onboarding/Styled.js
> changed button color style to match updated figma

- merch-dropper/src/components/Dashboard/Dashboard.js
- merch-dropper/src/components/Onboarding/Styled.js
> removed the welcome div and fixed text color on 2 buttons

- merch-dropper/src/components/Onboarding/Styled.js
> minor fix on a button

- merch-dropper/package.json
- merch-dropper/src/components/Component-Styles/addProduct-styles.js
- merch-dropper/src/components/Shirt/AddProduct.js
- merch-dropper/src/components/Shirt/AddProductToTable.js
- merch-dropper/yarn.lock
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Complete, but not tested (may need new tests)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
> add loader to addproduct

- merch-dropper/src/components/Dashboard/Inventory.js
- merch-dropper/src/components/Dashboard/InventoryCard.js
- merch-dropper/src/components/Dashboard/InventoryList.js
> Corrected inventory styling to match Settings component in width

- merch-dropper/src/components/Dashboard/Inventory.js
- merch-dropper/src/components/Dashboard/InventoryCard.js
- merch-dropper/src/components/Dashboard/InventoryList.js
- merch-dropper/src/components/Onboarding/CreateStore.js
> Added comments explaining CreateStore and Inventory-related components

- merch-dropper/src/components/NavBar.js
> change to dynamic url

- merch-dropper/src/components/Onboarding/StripeConnect.js
Potential fix for tests cors issue
> Removed www from the skipsetup redirect

- merch-dropper/src/components/Dashboard/Settings.js
- merch-dropper/src/components/Dashboard/Styled.js
I looked into the cors issue and couldn't reproduce it. Made the settings dynamic to cover ourselves a bit. I added a Connect to Stripe button if the user isn't connected but there is no functionality (next Release Canvas issue)
Settings in Dashboard are no longer static and show whether stripe is connected or not. If user is connected it should show the number, if not it will accurately say so. 
> Bug/cors issue in Settings

- merch-dropper/src/components/Auth/auth_config.json
- merch-dropper/src/components/Cart/Checkout.js
- merch-dropper/src/components/Dashboard/InventoryCard.js
- merch-dropper/src/components/Dashboard/InventoryList.js
- merch-dropper/src/components/Onboarding/CreateStore.js
- merch-dropper/src/components/Onboarding/StripeConnect.js
- merch-dropper/src/components/ProductDisplay.js
- merch-dropper/src/components/ProductDisplayDomain.js
- merch-dropper/src/components/Shirt/AddProduct.js
- merch-dropper/src/components/Shirt/AddProductToTable.js
- merch-dropper/src/components/Shirt/DesignHandler.js
- merch-dropper/src/components/Shirt/HandleScalableMockup.js
- merch-dropper/src/components/StripeButton.js
- merch-dropper/src/store/actions/index.js
- merch-dropper/src/utils/axiosWithAuth.js
switched merchdropper-production api to merch-dropper api
> Switched every 1st api call to call the 2nd

- merch-dropper/src/App.js
- merch-dropper/src/components/Auth/auth_config.json
- merch-dropper/src/components/NavBar.js
Fixing redirect bug
Issue is when clicking on sign in or get started, the link doesn't grant access.
> Fixed Navbar & redirect for now

- merch-dropper/src/components/NavBar.js
removing one of the store_name declaration
> Fix 2 store_name

- merch-dropper/src/components/Onboarding/CreateStore.js
Added console.log(profile) which contains email to give to be (to be sure that this isn't the problem
> Addition of console.log(profile) to CreateStore.js

- merch-dropper/src/components/Auth/auth_config.json
> updated audience

- merch-dropper/src/components/Cart/Checkout.js
- merch-dropper/src/components/Dashboard/InventoryList.js
> add useDispatch hook dependency

- merch-dropper/src/components/Cart/CartDropDown.js
- merch-dropper/src/components/Cart/Checkout.js
- merch-dropper/src/components/Cart/ShippingAddress.js
- merch-dropper/src/components/ProductCard.js
- merch-dropper/src/components/ProductDisplay.js
- merch-dropper/src/components/ProductDisplayDomain.js
- merch-dropper/src/store/actions/index.js
- merch-dropper/src/store/reducers/QuoteReducer.js
> fixed issue with getting quote

- merch-dropper/src/components/Dashboard/InventoryList.js
- merch-dropper/src/components/ProductDisplay.js
- merch-dropper/src/components/Shirt/AddProductToTable.js
- merch-dropper/src/components/StripeButton.js
- merch-dropper/src/store/actions/index.js
- merch-dropper/src/utils/axiosWithAuth.js
Co-dependent on backend with same(similar lol) branch name
Application fee and successful payments
> Fix application fee frontend branch

- merch-dropper/src/components/Cart/CartDropDown.js
- merch-dropper/src/components/Cart/Checkout.js
- merch-dropper/src/components/Cart/ShippingAddress.js
- merch-dropper/src/components/CloudinaryWidget.js
- merch-dropper/src/components/ProductCard.js
- merch-dropper/src/components/ProductDisplay.js
- merch-dropper/src/components/ProductDisplayDomain.js
- merch-dropper/src/components/Shirt/AddProductToTable.js
- merch-dropper/src/components/Shirt/DesignShirt.js
- merch-dropper/src/components/Shirt/HandleScalableMockup.js
- merch-dropper/src/store/actions/index.js
> deleted my console.logs that are no longer needed

- merch-dropper/src/components/StripeButton.js
> Finishes buyer can buy an item

- merch-dropper/src/components/Component-Styles/Footer.js
- merch-dropper/src/components/Component-Styles/Navbar-styles.js
- merch-dropper/src/components/Footer.js
- merch-dropper/src/components/Home.js
- merch-dropper/src/components/NavBar.js
> updating styles for mobile

- merch-dropper/public/index.html
- merch-dropper/src/App.css
- merch-dropper/src/App.js
- merch-dropper/src/components/Component-Styles/Footer.js
- merch-dropper/src/components/Component-Styles/Home.js
- merch-dropper/src/components/Component-Styles/NavBar.js
- merch-dropper/src/components/Footer.js
- merch-dropper/src/components/Home.js
- merch-dropper/src/components/NavBar.js
- merch-dropper/src/store/reducers/ProductReducers.js
> Fix landing page design

- merch-dropper/src/components/NavBar.js
> put icon back in navbar

- merch-dropper/src/components/Dashboard/Settings.js
Fixed create store if statement
Removing the ! before store
> Fixed create store if statement

- merch-dropper/src/components/Home.js
See title
Redirect from create store in landing page
> add auth0 hook to create store button

- merch-dropper/src/components/NavBar.js
Addition of logic & css your store btn
Fixed Your Store css
> Addition of logic & css your store btn

- merch-dropper/src/components/Cart/Checkout.js
> Update shipping and total to be $0 if cart items removed

- merch-dropper/src/components/NavBar.js
- merch-dropper/src/components/SideDrawer.js
> add inDevelop to SideDrawer and comment out/remove irrelevant code

- merch-dropper/src/components/Dashboard/InventoryCard.js
- merch-dropper/src/components/Dashboard/InventoryList.js
- merch-dropper/src/components/ProductDisplayDomain.js
> fixed delete item and product display

- merch-dropper/src/components/Shirt/AddProduct.js
- merch-dropper/src/components/Shirt/AddProductToTable.js
Can add products locally again.
Products weren't adding locally
> swap hard code axios to axioswithenv

- merch-dropper/.babelrc
- merch-dropper/package.json
- merch-dropper/yarn.lock
Addition of babel-plugin-transform-remove-console to remove logs in build
> Addition of babel-plugin-transform-remove-console

- merch-dropper/src/components/Cart/Checkout.js
- merch-dropper/src/components/NavBar.js
- merch-dropper/src/index.js
> Updated userID in navbar.js

- merch-dropper/src/components/Cart/Checkout.js
Updated orderToken
Maybe fixes our orderToken issue (tested)
> Updated orderToken
